
CREATE TABLE [UserInfo] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[ID] NVARCHAR(50),
	[Password] NVARCHAR(50),
	[UserName] NVARCHAR(50),
	[Language] NVARCHAR(50),
	[Email] NVARCHAR(50),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Role] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[RoleName] NVARCHAR(50),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [RoleUser] (
	[GUID] UNIQUEIDENTIFIER,
	[RoleUID] UNIQUEIDENTIFIER UNIQUE,
	[UserUID] UNIQUEIDENTIFIER,
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Pages] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[URL] NVARCHAR(255),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Menu] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[DisplayName] NVARCHAR(50),
	[ParentUID] UNIQUEIDENTIFIER,
	[PageUID] UNIQUEIDENTIFIER,
	[Level] SMALLINT,
	[Sortby] SMALLINT,
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [RoleAuth] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[RoleUID] UNIQUEIDENTIFIER,
	[MenuUID] UNIQUEIDENTIFIER,
	PRIMARY KEY([GUID])
);
GO

ALTER TABLE [Role]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleUser]([RoleUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [UserInfo]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleUser]([UserUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Pages]
ADD FOREIGN KEY([GUID]) REFERENCES [Menu]([PageUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Role]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleAuth]([RoleUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Menu]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleAuth]([MenuUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO