
CREATE TABLE [UserInfo] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[ID] NVARCHAR(50),
	[Password] NVARCHAR(50),
	[UserName] NVARCHAR(50),
	[Language] NVARCHAR(50),
	[Email] NVARCHAR(50),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Roles] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[RoleName] NVARCHAR(50),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [RoleUser] (
	[GUID] UNIQUEIDENTIFIER,
	[RoleUID] UNIQUEIDENTIFIER UNIQUE,
	[UserUID] UNIQUEIDENTIFIER,
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Pages] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[MainTitle] NVARCHAR(25),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [Menu] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[PageUID] UNIQUEIDENTIFIER,
	[ParentUID] UNIQUEIDENTIFIER,
	[Hierarchy] SMALLINT,
	[Sortby] SMALLINT,
	[DisplayName] NVARCHAR(50),
	[Description] NVARCHAR(50),
	[URL] NVARCHAR(255),
	[IconLeft] NVARCHAR(255),
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [RoleMenu] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[RoleUID] UNIQUEIDENTIFIER,
	[MenuUID] UNIQUEIDENTIFIER,
	PRIMARY KEY([GUID])
);
GO

CREATE TABLE [PageAuth] (
	[GUID] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[PageUID] UNIQUEIDENTIFIER,
	[RoleUID] UNIQUEIDENTIFIER,
	[Add] CHAR(1),
	[Delete] CHAR(1),
	[Modify] CHAR(1),
	PRIMARY KEY([GUID])
);
GO

ALTER TABLE [Roles]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleUser]([RoleUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [UserInfo]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleUser]([UserUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Pages]
ADD FOREIGN KEY([GUID]) REFERENCES [Menu]([PageUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Roles]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleMenu]([RoleUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Menu]
ADD FOREIGN KEY([GUID]) REFERENCES [RoleMenu]([MenuUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Pages]
ADD FOREIGN KEY([GUID]) REFERENCES [PageAuth]([PageUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Roles]
ADD FOREIGN KEY([GUID]) REFERENCES [PageAuth]([RoleUID])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO